services:
    neriping:
        image: ghcr.io/littlebitstudios/neriping:latest
        container_name: neriping
        restart: unless-stopped
        volumes:
            - ./config:/config:z # the z is there for podman users. it can be removed if you're using docker.
